<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Allow different timings for each day__13ef44</name>
   <tag></tag>
   <elementGuidId>a0a02f5a-5288-4121-8f78-3ca3334a031b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[id=&quot;allowDifferentSessionForEachDay&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='allowResOnDiferentSessionOnDifferentDays']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Allow Reservations on different session on different days&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b4738798-08c3-4f80-a030-33cd06920b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>allowResOnDiferentSessionOnDifferentDays</value>
      <webElementGuid>3878fa27-adfa-4c83-a67a-1cfbc358afab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>4a9cb18d-72e6-4cef-a95e-2c72f8e6e602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>5c69f22f-3013-4cee-8c8c-baa297b29423</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>allowResOnDiferentSessionOnDifferentDays</value>
      <webElementGuid>20161dcf-d1c2-495b-9238-405ebe2f1c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_oldvalue</name>
      <type>Main</type>
      <value>unchecked</value>
      <webElementGuid>1b3a1a43-2398-4f06-82df-968cccf763a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;allowResOnDiferentSessionOnDifferentDays&quot;)</value>
      <webElementGuid>7d87fd44-60a7-4fc6-aa1a-9284b0880a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_NS - Event/iframe_Confirm_landingFrame</value>
      <webElementGuid>22c0b919-3b6e-4fe8-9487-1125d50bace5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='allowResOnDiferentSessionOnDifferentDays']</value>
      <webElementGuid>24b2ef77-8a99-4d2a-abb2-ca37eeb98317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='allowResOnDiferentSessionOnDifferentDaysDiv']/div/input</value>
      <webElementGuid>69ab7977-c762-4356-8c74-9462d31c7fd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div[2]/div[6]/div/div/input</value>
      <webElementGuid>c1a73c49-c84b-4d7a-8a7d-70080792f5b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'allowResOnDiferentSessionOnDifferentDays' and @type = 'checkbox' and @id = 'allowResOnDiferentSessionOnDifferentDays']</value>
      <webElementGuid>53075a57-9981-4825-bdc9-28fb0c5f18d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
